server:
  port: 8088
spring:
  redis:
    database: 0
    host: 10.100.23.156
    port: 6379
    password:
    timeout: 10000
    pool:
      max-active: 8 #连接池最大连接数（使用负值表示没有限制）
      max-wait: -1  #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8   #连接池中的最大空闲连接
      min-idle: 0   #连接池中的最小空闲连接
  #数据源配置
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecrmdb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: 123456