server:
  port: 8088
spring:
  redis:
    host: 10.100.23.156
    port: 6379
    password:
  #数据源配置
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecrmdb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: 123456