server:
  port: 8088
spring:
  application:
    name: sword
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10000
    jedis:
      pool:
        max-idle: 8
        max-wait:
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/ecrmdb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: ${oliver.rabbitmq.host}
    port: 5672
    username: ${oliver.rabbitmq.username}
    password: ${oliver.rabbitmq.password}
    virtual-host: ${oliver.rabbitmq.vitualhost}
# swagger设置
swagger:
  enable: true
  title: Oliver Swagger for sword
  description: 基于swagger-spring-boot-starter的工具
  version: 1.0.0.RELEASE
  contact:
    name: Oliver Wang
    url: shein.com
    email: oliver.wang@shein.com
  global-operation-parameters[0]:
    name: access_token
    description: user access token
    modelRef: string
    parameterType: header
    required: true
  global-response-message[1]:
    name: timestamp
    description: access timestamp
    modelRef: int
    parameterType: header
    required: false
  apply-default-response-messages: true
  global-response-message:
    get[0]:
      code: 401
      message: 401get
    get[1]:
      code: 500
      message: 500get
      modelRef: ERROR
  ui-config:
    json-editor: false
    show-request-headers: true
    request-timeout: 5000

  #消除 Illegal DefaultValue null for parameter type integer
logging:
  level.io.swagger.models.parameters.AbstractSerializableParameter: error