@startuml
 actor 业务系统管理人员
 actor 会员系统配置管理者

 ==线下交互信息==

 业务系统管理人员 --> 会员系统配置管理者: 申请接入邮件需要的系统码和业务场景编码
 业务系统管理人员 --> 会员系统配置管理者: 同步场景需求参数类型
 业务系统管理人员 --> 会员系统配置管理者: 同步相关的占位符信息

 ==结束线下交互信息==
 会员系统配置管理者 -> ECRM系统: 维护系统和场景信息
 会员系统配置管理者 -> ECRM系统: 维护场景参数信息
 会员系统配置管理者 -> ECRM系统: 维护系统占位符信息
 会员系统配置管理者 -> ECRM系统: 配置场景对应的模板信息

 database ECRM维护数据
 ECRM系统 -> ECRM维护数据: 数据持久化

@enduml