
@startuml
skinparam handwritten true
 participant 业务方 as business
 participant ECRM系统 as ecrm
  database ECRM系统数据库 as ecrmdb
 participant 邮件发送方 as EDMZENDESK


 business -> ecrm: 支持Rabbit异步请求和调API请求
 ecrm -> ecrmdb: 数据持久化
 alt  立即发送
 activate ecrm
 ecrm -> ecrm : 查询模板 && 匹配站位符 && 选择发送渠道
 ecrm -> EDMZENDESK: 请求邮件发送
 deactivate ecrm

 else 非立即发送
 ecrm -> ecrmdb: 获取待发送记录
 activate ecrm
 ecrm -> ecrm : 查询模板 && 匹配站位符 && 选择发送渠道
 ecrm -> EDMZENDESK: 批量请求邮件发送
 deactivate ecrm
 end

 EDMZENDESK -> ecrm: 反馈邮件发送情况
 ecrm -> ecrmdb: 更改记录状态
 ecrm -> business : 同步发送结果

@enduml